### ISSUE TITLE
Translate Readme

### ISSUE THREAD

**Issue by smellai** [arduino/reference-jp#12]

**Comment by akash73** [comment]
@tanoueakira hi, can you translate when you have time, the readme too? 
thanks

**Comment by tanoueakira** [comment]
I translated the README.adoc.
Please check it.

**Comment by akash73** [comment]
Hi , we found a mistake:
we removed all the references to Manutius, and updated the first part of the read me where manutius was mentionend.

this is the updated file 
https://github.com/arduino/reference-en/blob/master/README.adoc

can you adapt it please?

thanks

**Comment by akash73** [comment]
closed via #18
