### ISSUE TITLE
Translate homepage texts and categories

### ISSUE THREAD

**Issue by smellai** [arduino/reference-jp#13]
functions
Main
Digital I/O
Analog I/O
Arduino DUE only
Advanced I/O
Time
Math
Trigonometry
Random Numbers
Bits and Bytes
External Interrupts
Interrupts
Communication
Serial
Stream
USB (Leonardo and DUE only)
Keyboard
Mouse

variables
Constants
Conversion
Data Types
Variable Scope & Qualifiers
Utilities

structure
Control Structure
Further Syntax
Arithmetic Operators
Comparison Operators
Boolean Operators
Pointer Access Operators
Bitwise Operators
Compound Operators

Language Reference

Arduino programming language can be divided in three main parts: structure, values (variables and constants), and functions.

- Menu:
Language
Functions
Variables
Structure
Libraries
Glossary

- Button Label:
Edit this page

- License Note: 
`The Arduino Reference text is licensed under a <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noopener">Creative Commons Attribution-Share Alike 3.0 License</a>.`
`Find anything that can be improved? <a href="https://github.com/arduino/reference-en">Suggest corrections and new documentation via GitHub.</a>`

**Comment by akash73** [comment]
@tanoueakira can you translate also this? thanks

**Comment by tanoueakira** [comment]
functions
 Main--メイン
 Digital I/O--デジタル入出力
 Analog I/O--アナログ入出力
 Arduino DUE only--Arduino DUE のみ
 Advanced I/O--応用入出力
 Time--時間
 Math--数学
 Trigonometry--三角関数
 Random Numbers--乱数
 Bits and Bytes--ビットとバイト
 External Interrupts--外部割り込み
 Interrupts--割り込み
 Communication--コミュニケーション
 Serial--シリアル
 Stream--Stream   (I think that English is better)
 USB (Leonardo and DUE only)--USB（LeonardoとDUEのみ）
 Keyboard--キーボード
 Mouse--マウス

variables
 Constants--定数
 Conversion--型変換
 Data Types--データ型
 Variable Scope & Qualifiers--変数のスコープと修飾子
 Utilities--ユーティリティ

structure
 Control Structure--制御文
 Further Syntax--補足の構文
 Arithmetic Operators--算術演算子
 Comparison Operators--比較演算子
 Boolean Operators--ブール演算子
 Pointer Access Operators--ポインタ
 Bitwise Operators--ビット演算子
 Compound Operators--複合演算子

Language Reference--言語リファレンス

Arduino programming language can be divided in three main parts: structure, values (variables and constants), and functions.
Arduinoのプログラミング言語は，主に3つのパートに分割することができます（構文，値（変数と定数）および関数）

•Menu:
 Language--言語
 Functions--関数
 Variables--変数
 Structure--構文
 Libraries--ライブラリ
 Glossary--用語集


•Button Label:
 Edit this page--このページを編集する


•License Note:
 The Arduino Reference text is licensed under a <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noopener">Creative Commons Attribution-Share Alike 3.0 License</a>. 
 Find anything that can be improved? <a href="https://github.com/arduino/reference-en">Suggest corrections and new documentation via GitHub.</a> 

Arduinoリファレンスの文章は <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noopener">Creative Commons Attribution-Share Alike 3.0 License</a>の下でライセンスされています. 
 改善すべき部分がありますか？<a href="https://github.com/arduino/reference-en">GitHubを通じて，訂正や新しいドキュメントの提案をお願いします.</a> 

※https://github.com/arduino/reference-en　→　reference-jp ?

**Comment by tanoueakira** [comment]
I have translated these words!

**Comment by smellai** [comment]
Hi @tanoueakira , thank you so much!
Now here https://cdn.arduino.cc/reference/jp/ you will se only the translated pages. I updated them to use the translated subcategory:
```
---
title: pulseIn()
categories: [ "Functions" ]
subCategories: [ "応用入出力" ]
---
```

as soon as the other subcategories will be updated, they will displayed in the index
