### ISSUE TITLE
read me, modified Creative commons license version

### ISSUE THREAD

**Issue by akash73** [arduino/reference-jp#17]
Hi, we have modified the CC version from 4.0 to 3.0.
here is the new text 
Please note that your contribution to the Arduino Reference is licensed under a Creative Commons Attribution-Share Alike 3.0 License. see https://creativecommons.org/licenses/by-sa/3.0/

@tanoueakira

**Comment by tanoueakira** [comment]
I chenged the licence text and mistake.

thanks!

**Comment by akash73** [comment]
closed via #18
