### ISSUE TITLE
Translate title and description for the site

### ISSUE THREAD

**Issue by smellai** [arduino/reference-jp#9]
English Title: Arduino Reference
English Description: The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.

Functions Title: For controlling the Arduino board and performing computations.
Variables Title: Arduino data types and constants.
Structure Title: The elements of Arduino (C++) code.

**Comment by akash73** [comment]
@tanoueakira please would you like to translate also what @smellai wrote ?
thanks!

**Comment by akash73** [comment]
you can see the rendered page here:
https://cdn.arduino.cc/reference/jp/

**Comment by tanoueakira** [comment]
These are the translated titles.

English Title: Arduinoリファレンス
English Description: Arduinoのプログラム言語のリファレンスです．　「関数」，「変数と定数」および「制御文と演算子」で構成されています．

Functions Title: Arduinoで計算や制御をするための関数
Variables Title: Arduinoのデータ型と定数
Structure Title: Arduinoコード(C++)の要素

**Comment by smellai** [comment]
Thanks!
